# Generated by Django 5.1.7 on 2025-04-24 15:13

import CampusMart.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CampusMart', '0004_user_auth_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=CampusMart.models.upload_to),
        ),
    ]
