# Generated by Django 5.2 on 2025-04-30 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CampusMart', '0008_userextralistings_extra_listings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextralistings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CampusMart.user'),
        ),
    ]
