# Generated by Django 5.2 on 2025-04-30 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CampusMart', '0010_alter_userextralistings_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextralistings',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CampusMart.user'),
        ),
    ]
