# Generated by Django 5.2 on 2025-04-30 02:25

import django.db.models.deletion
from django.db import migrations, models

def set_user_on_existing_extralistings(apps, schema_editor):
    User = apps.get_model('CampusMart', 'User')
    UserExtraListings = apps.get_model('CampusMart', 'UserExtraListings')

    default_user = User.objects.first()  # Or filter for a specific fallback user
    for listing in UserExtraListings.objects.filter(user__isnull=True):
        listing.user = default_user
        listing.save()

class Migration(migrations.Migration):

    dependencies = [
        ('CampusMart', '0012_alter_userextralistings_user'),
    ]

    operations = [
        migrations.RunPython(set_user_on_existing_extralistings),
        migrations.AlterField(
            model_name='userextralistings',
            name='user',
            field=models.OneToOneField(to='CampusMart.User', on_delete=models.CASCADE),
        ),
    ]



