# Generated by Django 5.2 on 2025-04-30 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CampusMart', '0013_alter_userextralistings_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextralistings',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
